import Foundation

enum ReportComposer {
    private static var moneyFormatters: [String: NumberFormatter] = [:]
    private static let formatterLock = NSLock()

    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter
    }()

    static func reportText(for order: WorkOrder, history: [WorkOrder], currencyCode: String? = nil) -> String {
        let code = normalizedCurrencyCode(currencyCode)
        let actions = order.actions
            .sorted { $0.timestamp < $1.timestamp }
            .map { "• \($0.text) (\(dateFormatter.string(from: $0.timestamp)))" }
            .joined(separator: "\n")

        let beforeCount = order.photos.filter { $0.stage == .before }.count
        let progressCount = order.photos.filter { $0.stage == .inProgress }.count
        let afterCount = order.photos.filter { $0.stage == .after }.count

        let totalPrice = formattedMoney(order.totalCost, currencyCode: code)
        let laborPrice = formattedMoney(order.laborCost, currencyCode: code)
        let materialsPrice = formattedMoney(order.materialsCost, currencyCode: code)

        return """
        WorkProof Report

        Client: \(order.clientName)
        Address: \(order.address.isEmpty ? "Not specified" : order.address)
        Job Type: \(order.jobType)
        Status: \(order.status.rawValue)
        Created: \(dateFormatter.string(from: order.createdAt))

        Photo Summary:
        • Before: \(beforeCount)
        • In Progress: \(progressCount)
        • After: \(afterCount)

        Work Log:
        \(actions.isEmpty ? "• No actions recorded" : actions)

        Costs:
        • Currency: \(code)
        • Labor: \(laborPrice)
        • Materials: \(materialsPrice)
        • Total: \(totalPrice)

        Time Spent:
        \(formattedDuration(order.elapsedTime()))

        Client History:
        \(history.isEmpty ? "No previous orders" : "\(history.count) previous order(s)")

        Generated by WorkProof on \(dateFormatter.string(from: .now)).
        """
    }

    static func formattedMoney(_ value: Double, currencyCode: String? = nil) -> String {
        let code = normalizedCurrencyCode(currencyCode)
        let formatter = moneyFormatter(for: code)
        return formatter.string(from: NSNumber(value: value)) ?? "\(code) 0"
    }

    static func formattedDuration(_ seconds: TimeInterval) -> String {
        let totalSeconds = max(0, Int(seconds))
        let hours = totalSeconds / 3600
        let minutes = (totalSeconds % 3600) / 60
        let remainingSeconds = totalSeconds % 60

        if hours > 0 {
            return "\(hours)h \(minutes)m"
        }

        if minutes > 0 {
            return "\(minutes)m \(remainingSeconds)s"
        }

        return "\(remainingSeconds)s"
    }
}

private extension ReportComposer {
    static func normalizedCurrencyCode(_ currencyCode: String?) -> String {
        let candidate = currencyCode?.isEmpty == false ? currencyCode : CurrencySettings.selectedCurrencyCode
        let code = (candidate ?? CurrencySettings.defaultCode).uppercased()
        return CurrencyOption(rawValue: code)?.rawValue ?? CurrencySettings.defaultCode
    }

    static func moneyFormatter(for currencyCode: String) -> NumberFormatter {
        formatterLock.lock()
        defer { formatterLock.unlock() }

        if let cached = moneyFormatters[currencyCode] {
            return cached
        }

        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.maximumFractionDigits = 0
        formatter.currencyCode = currencyCode
        formatter.locale = Locale.current
        moneyFormatters[currencyCode] = formatter
        return formatter
    }
}
